"""add board_type to boards

Revision ID: 01a3141516d1
Revises: 6b838ff8246e
Create Date: 2026-02-08 17:11:28.176024

"""

from alembic import op
import sqlalchemy as sa


revision = "01a3141516d1"
down_revision = "6b838ff8246e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boards", sa.Column("board_type", sa.String(), nullable=True))
    op.execute("UPDATE boards SET board_type='general' WHERE name='자유게시판'")
    op.execute("UPDATE boards SET board_type='qna' WHERE name='Q&A'")
    op.execute("UPDATE boards SET board_type='notice' WHERE name='공지사항'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boards", "board_type")
    # ### end Alembic commands ###
