"""add photo metadata columns

Revision ID: 51feb0521647
Revises: de7971368f01
Create Date: 2026-01-28 17:08:45.014373

"""

from alembic import op
import sqlalchemy as sa

revision = "51feb0521647"
down_revision = "de7971368f01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("filename", sa.String(), nullable=True))
    op.add_column("photos", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("photos", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("photos", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("photos", sa.Column("uploader_id", sa.Integer(), nullable=True))
    op.add_column(
        "photos",
        sa.Column(
            "display_order", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column("photos", sa.Column("caption", sa.Text(), nullable=True))
    op.create_foreign_key(
        "photos_uploader_id_fkey", "photos", "users", ["uploader_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("photos_uploader_id_fkey", "photos", type_="foreignkey")
    op.drop_column("photos", "caption")
    op.drop_column("photos", "display_order")
    op.drop_column("photos", "uploader_id")
    op.drop_column("photos", "height")
    op.drop_column("photos", "width")
    op.drop_column("photos", "file_size")
    op.drop_column("photos", "filename")
    # ### end Alembic commands ###
