"""added submissions cascade to problems

Revision ID: b5594514de8c
Revises: 40734c3ffdfb
Create Date: 2026-03-15 05:36:01.366159

"""
from alembic import op
import sqlalchemy as sa


revision = 'b5594514de8c'
down_revision = '40734c3ffdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
