from typing import Any, Optional

class Response:
    status_code: int
    def json(self) -> Any: ...

class ASGITransport:
    def __init__(self, app: Any, lifespan: str = ...) -> None: ...

class AsyncClient:
    def __init__(self, *, transport: ASGITransport, base_url: str) -> None: ...
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(
        self, exc_type: Optional[type], exc: Optional[BaseException], tb: Optional[Any]
    ) -> None: ...
    async def get(self, url: str) -> Response: ...
